#
# Copyright (c) 2023 Valentin Rusche.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#

float32 current_tick
carla_msgs/CarlaEgoVehicleInfo vehicle_info
carla_msgs/CarlaEgoVehicleStatus vehicle_status
bool is_ego_vehicle
carla_waypoint_types/CarlaWaypoint current_waypoint
float32 geo_latitude
float32 geo_longitude
float32 geo_altitude
