#
# Copyright (c) 2023 Valentin Rusche.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#
uint32 id
---
carla_actor_state_types/CarlaActorState actor_state
